import "./globals.css";
import { Toaster } from "react-hot-toast";

export const metadata = {
  title: "EveryOneZone",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
      suppressHydrationWarning 
      className={`font-mono`}>
        {children}
        <Toaster richColors position="top-center"/>
      </body>
    </html>
  );
}
